######################################################################
# Automatically generated by qmake (3.1) Wed Apr 22 09:33:10 2026
######################################################################

QT += core network sql network

TEMPLATE = app
TARGET = WangPanServer

# Sources
SOURCES += \
    main.cpp \
    server.cpp \
    clienthandler.cpp \
    databasemanager.cpp \
    filemanager.cpp \
    usermanager.cpp \
    permissionmanager.cpp \
    logmanager.cpp \
    monitor.cpp

# Headers
HEADERS += \
    server.h \
    clienthandler.h \
    databasemanager.h \
    filemanager.h \
    usermanager.h \
    permissionmanager.h \
    logmanager.h \
    monitor.h

# Include paths
INCLUDEPATH += .

# Compiler flags
QMAKE_CXXFLAGS += -std=c++11

# Platform specific settings
win32 {
    LIBS += -lws2_32
}

unix {
    LIBS += -lpthread
}
