######################################################################
# Automatically generated by qmake (3.1) Wed Apr 22 09:32:45 2026
######################################################################

QT += core gui network widgets sql concurrent

TEMPLATE = app
TARGET = WangPanClient

# Sources
SOURCES += \
    main.cpp \
    mainwindow.cpp \
    loginwindow.cpp \
    registerwindow.cpp \
    networkmanager.cpp \
    user.cpp \
    filemanager.cpp \
    previewwindow.cpp

# Headers
HEADERS += \
    mainwindow.h \
    loginwindow.h \
    registerwindow.h \
    networkmanager.h \
    user.h \
    filemanager.h \
    previewwindow.h

# Forms
FORMS += \
    mainwindow.ui \
    loginwindow.ui \
    registerwindow.ui \
    previewwindow.ui

# Resources
RESOURCES += \
    resources.qrc

# Include paths
INCLUDEPATH += .

# Compiler flags
QMAKE_CXXFLAGS += -std=c++11

# Encoding
CODECFORTR = UTF-8
CODECFORSRC = UTF-8

# Platform specific settings
win32 {
    LIBS += -lws2_32
}

unix {
    LIBS += -lpthread
}
